custom_records:
  - "www.baidu.com"
  - "wiki.eryajf.net"
cloud_providers:
  # ↓↓↓ -------------------------- 1. DNS提供商Tencent，请勿更改此行，如无需腾讯云的配置，可删除此段配置至 aliyun，该字段会作为标签注入到指标中
  tencent:
    # ↓↓↓ ------------------------ 2. 固定配置，无需更改
    accounts:
      # ↓↓↓ ---------------------- 3. 腾讯云账号配置，可配置多个，给每个账号取个名字，如 t1、t2，该字段会作为标签注入到指标中
      - name: t1
        secretId: "xxxxx"
        secretKey: "xxxxx"
      - name: t2
        secretId: "xxxxx"
        secretKey: "xxxxx"
  aliyun:
    accounts:
      - name: a1
        secretId: "xxxxx"
        secretKey: "xxxxx"
  godaddy:
    accounts:
      - name: g1
        secretId: "xxxxx"
        secretKey: "xxxxx"
  amazon:
    accounts:
      - name: a1
        secretId: "xxxxx"
        secretKey: "xxxxx"
  dnsla:
    accounts:
      - name: d1
        secretId: "xxxxx"
        secretKey: "xxxxx"
  cloudflare:
    accounts:
      - name: a1
        secretId: "xxxxx" # 注册邮箱
        secretKey: "xxxxx" # ApiKey密钥
  # 目前支持 Tencent, Aliyun, Godaddy, DNALA, Amazon, Cloudflare，如需支持更多云厂商，请提交 issue，也欢迎 PR
